# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.urlLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlLineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout.addWidget(self.urlLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.segmentComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.segmentComboBox.setObjectName("segmentComboBox")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.segmentComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.segmentComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.filePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.filePathLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.horizontalLayout_3.addWidget(self.filePathLineEdit)
        self.selectFilePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFilePathButton.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.selectFilePathButton.setObjectName("selectFilePathButton")
        self.horizontalLayout_3.addWidget(self.selectFilePathButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.cookieTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.cookieTextEdit.setObjectName("cookieTextEdit")
        self.horizontalLayout_6.addWidget(self.cookieTextEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(400, 0))
        self.progressBar.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.speedLabel = QtWidgets.QLabel(self.centralwidget)
        self.speedLabel.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.speedLabel.setText("")
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_4.addWidget(self.speedLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_5.addWidget(self.resetButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_5.addWidget(self.downloadButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 85, 255);")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.segmentComboBox.setCurrentIndex(4)
        self.selectFilePathButton.clicked.connect(MainWindow.selectFilePath)
        self.resetButton.clicked.connect(MainWindow.resetParam)
        self.downloadButton.clicked.connect(MainWindow.startDownload)
        self.closeButton.clicked.connect(MainWindow.closeWindow)
        self.urlLineEdit.editingFinished.connect(MainWindow.changeUrlContent)
        self.segmentComboBox.currentIndexChanged['QString'].connect(MainWindow.segmentNumberChange)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "url"))
        self.label_2.setText(_translate("MainWindow", "分段数"))
        self.segmentComboBox.setCurrentText(_translate("MainWindow", "64"))
        self.segmentComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.segmentComboBox.setItemText(1, _translate("MainWindow", "5"))
        self.segmentComboBox.setItemText(2, _translate("MainWindow", "10"))
        self.segmentComboBox.setItemText(3, _translate("MainWindow", "32"))
        self.segmentComboBox.setItemText(4, _translate("MainWindow", "64"))
        self.segmentComboBox.setItemText(5, _translate("MainWindow", "128"))
        self.segmentComboBox.setItemText(6, _translate("MainWindow", "256"))
        self.label_5.setText(_translate("MainWindow", "保存路径"))
        self.selectFilePathButton.setText(_translate("MainWindow", "选择"))
        self.label_3.setText(_translate("MainWindow", "cookie(可选)"))
        self.label_4.setText(_translate("MainWindow", "下载进度"))
        self.resetButton.setText(_translate("MainWindow", "重置"))
        self.downloadButton.setText(_translate("MainWindow", "下载"))
        self.closeButton.setText(_translate("MainWindow", "关闭"))

